### PR TITLE
Fix output

### PR DESCRIPTION
**Pull request by lukasz-mitka**

### CODE REVIEW

**Comment by sondrelg** [comment]
Thanks @lukasz-mitka. Would you mind fixing the test as well?

**Comment by lukasz-mitka** [comment]
Done

**Comment by den-is** [comment]
You guys rock!!!

**Comment by lukasz-mitka** [comment]
@sondrelg waiting for a release then!

**Comment by sondrelg** [comment]
v2 released, finally. Thanks for all the great help @lukasz-mitka :clap:

**Pull request merged**
