### PR TITLE
Fix unhandled exception raised at runtime: 'x-ratelimit-remaining'

### PR DESCRIPTION
**Pull request by den-is**
Fixing https://github.com/snok/container-retention-policy/issues/57

P.S.: My default [black](https://github.com/psf/black) config formatted code a little bit.

### CODE REVIEW

**Comment by JonasKs** [comment]
Hi 😊 Thanks for the PR. 

> P.S.: My default [black](https://github.com/psf/black) config formatted code a little bit.

It's already implemented black in this project (see the failing `linting` pipeline), but our config differs from yours. It's used through [`pre-commit`](https://github.com/snok/container-retention-policy/blob/main/.pre-commit-config.yaml). Simply write `pre-commit install` in your repo, and then `pre-commit run --all-files` and it'll be fixed.  (Require you to [install `pre-commit` first](https://pre-commit.com/))

**Comment by sondrelg** [comment]
This looks good to me. Just curious @den-is, have you had a chance to test this version of the code on your own projects? I've migrated my images to ECR, so no longer have a real project to try things like this on hehe :shrug:

**Comment by den-is** [comment]
> This looks good to me. Just curious @den-is, have you had a chance to test this version of the code on your own projects? I've migrated my images to ECR, so no longer have a real project to try things like this on hehe 🤷

Yes, it was/is successfully working for months on a scheduled basis.
But action/execution still was hitting GH rate-limits, Looks like this async code requires some "semaphores". While it was hitting GH rate-limits it still was doing its job and was cleaning the registry.

I'm not working on that project and don't have access to such GHCR anymore.

**Comment by sondrelg** [comment]
OK sounds good. I'll try and get this released now! :+1:

**Pull request merged**
