### PR TITLE
Update set-output syntax

### LINKED ISSUE #46: The `set-output` command is deprecated and will be disabled soon
Github Actions is deprecating `set-output` command soon.

image

```bash
Warning: The `set-output` command is deprecated and will be disabled soon. 
Please upgrade to using Environment Files. 
For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

So following lines need to be reviewed / fixed. 

https://github.com/snok/container-retention-policy/blob/main/.github/workflows/clean_packages.yml#L66

https://github.com/snok/container-retention-policy/blob/main/main.py#L509

https://github.com/snok/container-retention-policy/blob/main/main_tests.py#L578-L580

### PR DESCRIPTION
**Pull request by sondrelg**
Fixes #46

### CODE REVIEW

**Comment by jens-maus** [comment]
Any change to get this PR integrated and a new version of this action released soon? It has been a while already and the date is quickly approaching when GitHub will disable this obsolete set-output use.

**Comment by sondrelg** [comment]
Thanks for the reminder @jens-maus. I'll release it now :slightly_smiling_face:

**Comment by sondrelg** [comment]
I spoke too soon. We're due to release a new major version since merging https://github.com/snok/container-retention-policy/pull/36. We decided to wait for https://github.com/snok/container-retention-policy/pull/42 to get both breaking changes in one release.

When is the deadline for the switch?

**Comment by bdelavega-maralytix** [comment]
> When is the deadline for the switch?

Looks like 31-May-2023, per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Pull request merged**
