### PR TITLE
Add action outputs

### LINKED ISSUE #20: Ignore public images with more than 5000 downloads
Hi, thank you for your effort to create this action :)
I'm writing to ask you, about the possibility to ignore tags which has more than 5000 downloads? Currently, each run tries to remove the same tags which are unavailable to remove.

Thanks in advance,

### PR DESCRIPTION
**Pull request by sondrelg**
Resolves #20

### CODE REVIEW

**Review by Siemienik — APPROVED** [review]
It looks promising because it enables me to save this list into a file, and then cache it between runs, then constructs the ignore list based on it.

Thanks :) And have a good luck:)

**Comment by sondrelg** [comment]
Thanks for pointing that out @Siemienik.

 I just realized that actions can produce outputs; this might be the best way of resolving your use case. How about returning skipped images in a format that you can use in subsequent steps, like this?

```yaml
- name: Delete old images
  uses: snok/container-retention-policy@d7fe3656afc459bef9bb4990027569ac1ab4348b
  id: some-id
  with:
    ...
- name: Add skipped images to passlist
  run: |
    images="${{ steps.some-id.outputs.public-images-with-5000-downloads-or-more }}"
    ...
```

----------

This way you could really just dump the steps' output directly to a file. 

Thinking a little bit ahead, I suppose this *could* also be coupled with the `skip-tags` input to let you pass the file back to the action directly, but not quite sure what the best design would be for that yet.

**Comment by Siemienik** [comment]
It looks great and should resolve all troubles around these tags. I have one another idea if would you like to analize this one:

```yml
- name: Cache skip tags file
  uses: actions/cache@v2
  with:
    path: |
      ~/.github/workflows/skip-tags.txt
    key: container-retention-policy_skip-tags

- name: Delete old images
  uses: snok/container-retention-policy@d7fe3656afc459bef9bb4990027569ac1ab4348b
  id: some-id
  with:
     skip-tags: latest, production
     skip-tags-file : .github/workflows/skip-tags.txt # each line concats to `skip-tags`
     persist-skip-tags: true
```

WDYT?

**Comment by Siemienik** [comment]
@sondrelg, I made a message to you on gitter :)

**Comment by sondrelg** [comment]
Think I'm happy with adding outputs to the action in this manner. I renamed the public-images-with-over-5000-downloads output to needs-github-assistance, which seems a little more concise and actionable. 

As discussed in gitter, something like this might be a good implementation for a user wanting to skip these images in a subsequent run:

```yaml
- name: Cache(d) image versions to skip
  uses: actions/cache@v2
  with:
    path: skip-image-versions.txt
    key: image-versions-to-skip

- name: Delete old GHCR images
  uses: snok/container-retention-policy@v1
  id: arbitrary-id
  with:
     skip-tags: latest, production
     skip-tags-file : skip-image-versions.txt

- name: Write skipped tags to cache
  run: echo "${{ steps.arbitrary-id.outputs.needs-github-assistance }}" > skip-image-versions.txt
```

Before adding a `skip-tags-file` input, I just want to make sure that there's no way to just `cat` the file to pass it to `skip-tags` instead. 

If this _is_ possible, we probably still want to extend skip tags from skipping all tags, to also supporting `name:version` combinations, as that's not currently the case.

**Pull request merged**
